In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])


In [4]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:

np.ones((2, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:

np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:

np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [8]:

np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:

np.random.rand(3, 2)


array([[0.09328762, 0.44107032],
       [0.89949305, 0.12307192],
       [0.70733848, 0.87798616]])

In [10]:

np.random.randn(3, 2)

array([[-1.53409338,  0.55965663],
       [-0.53921253,  0.74735785],
       [-0.20305083,  0.15421705]])

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [12]:
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)



array([0.84147098, 0.90929743, 0.14112001])

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [14]:
arr = np.array([1, 2, 3, 4])
arr.sum()


np.int64(10)

In [15]:
arr.mean()


np.float64(2.5)

In [16]:

arr.max()


np.int64(4)

In [17]:

arr.min()


np.int64(1)

In [18]:

arr.std()

np.float64(1.118033988749895)

In [19]:
# 1D Arrays
arr = np.array([1, 2, 3, 4, 5])
arr[0]

arr[1:4]
arr[::2]



array([1, 3, 5])

In [20]:
# 2D Arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]



array([4, 5])

In [23]:
# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr >3
arr[mask]

array([4, 5])

In [24]:
# Reshape
arr = np.arange(6)
arr.reshape(2, 3)



array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))



array([1, 2, 3, 4])

In [26]:
# Stacking
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [27]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [30]:
# Save to a file
np.save('array.npy', arr)



In [31]:
# Load from a file
loaded_arr = np.load('array.npy')